# Generated by Django 4.2.21 on 2025-05-22 03:57

from django.db import migrations, models
from django.utils.text import slugify

def generate_slugs(apps, schema_editor):
    Influencer = apps.get_model('influencers', 'Influencer')
    for influencer in Influencer.objects.all():
        if not influencer.slug:
            base_slug = slugify(influencer.username)
            slug = base_slug
            counter = 1
            while Influencer.objects.filter(slug=slug).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            influencer.slug = slug
            influencer.save()

class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.RunPython(generate_slugs),
    ]
