# Generated by Django 4.2.21 on 2025-05-22 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0002_auto_20250521_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='influencer',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Verificado'),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de contacto'),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='engagement_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Tasa de engagement'),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='followers',
            field=models.PositiveIntegerField(default=0, verbose_name='Seguidores'),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='platform',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('twitter', 'Twitter')], default='instagram', max_length=20, verbose_name='Plataforma'),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='price_per_post',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio por publicación'),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True, verbose_name='Slug'),
        ),
    ]
