# Generated by Django 4.2.7 on 2025-04-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0003_campaign_influencers_alter_influencer_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencer',
            name='profile_picture',
        ),
        migrations.AlterField(
            model_name='influencer',
            name='category',
            field=models.CharField(choices=[('lifestyle', 'Lifestyle'), ('business', 'Business'), ('motivation', 'Motivation')], default='lifestyle', max_length=20),
        ),
    ]
