# Generated by Django 4.2.7 on 2025-04-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0004_remove_influencer_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
